### ISSUE TITLE
Issues installing package

### ISSUE THREAD

**Issue by rkarlssonlinner** [qlu-lab/PUMAS#1]
Hi,

I get the following error when I try to install the package according to the instructions in the README:

```
R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.6.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(devtools)
Loading required package: usethis
> install_github("qlu-lab/PUMAS")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`qlu-lab`) and repo name (`PUMAS`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.
```

**Comment by qlu-lab** [comment]
Hi,
Thank you so much for your feedback, the problem is about working directory of downloaded packages and is from our end. We offer 2 ways to install the package: 1) Through install_github from devtools which requires you to change the working directory to the place the package is loaded. 2)Clone and Github repo and load the package from there. 

I will suggest you to try second way with fewer efforts for now. So you can click on Clone or Download from github, unzip the package and double clicked on `pumas.Rproj.`
<img width="461" alt="Screen Shot 2019-10-21 at 3 31 44 PM" src="https://user-images.githubusercontent.com/33715415/67240852-eb436b00-f417-11e9-9ede-821b65eb4b57.png">

After that, you can go to  R > Build > Load All and the package is fully loaded. A example usage from direct download is attached.
<img width="1081" alt="Screen Shot 2019-10-21 at 3 26 36 PM" src="https://user-images.githubusercontent.com/33715415/67240964-234aae00-f418-11e9-86f9-9ff1a168b235.png">

Sorry for any concerns
